
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 6597707
	#The name of the modpack
	modpackName = "Velaris Circle"
	#The version of the modpack
	modpackVersion = "v2.0"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

