
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.wood_type]

		[types.wood_type.iceandfire]
			dreadwood = true

		[types.wood_type.cataclysm]
			chorus = true

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.endergetic]
			poise = true

		[types.wood_type.dungeons_and_combat]
			elden_oak = true

		[types.wood_type.deeperdarker]
			bloom = true
			echo = true

		[types.wood_type.natures_spirit]
			redwood = true
			sugi = true
			wisteria = true
			fir = true
			willow = true
			aspen = true
			maple = true
			cypress = true
			olive = true
			joshua = true
			ghaf = true
			palo_verde = true
			coconut = true
			cedar = true
			larch = true
			mahogany = true
			saxaul = true

		[types.wood_type.cinderscapes]
			scorched = true
			umbral = true

	[types.leaves_type]

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.deeperdarker]
			echo = true

		[types.leaves_type.natures_spirit]
			frosty_redwood = true
			redwood = true
			sugi = true
			wisteria = true
			white_wisteria = true
			part_white_wisteria = true
			blue_wisteria = true
			part_blue_wisteria = true
			pink_wisteria = true
			part_pink_wisteria = true
			purple_wisteria = true
			part_purple_wisteria = true
			frosty_fir = true
			fir = true
			willow = true
			aspen = true
			yellow_aspen = true
			red_maple = true
			orange_maple = true
			yellow_maple = true
			cypress = true
			olive = true
			joshua = true
			ghaf = true
			palo_verde = true
			coconut = true
			cedar = true
			larch = true
			mahogany = true
			saxaul = true

	[types.cake]

		[types.cake.natures_spirit]
			cheese_block = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.quark]
			vertical_planks = true
			post = true
			trapped_chest = true
			bookshelf = true
			chest = true
			stripped_post = true
			ladder = true
			hollow_log = true
			vertical_slab = true

		[entries.wood_type.twigs]
			table = true

		[entries.wood_type.handcrafted]
			counter = true
			corner_trim = true
			fancy_bed = true
			desk = true
			shelf = true
			nightstand = true
			cupboard = true
			dining_bench = true
			bench = true
			couch = true
			table = true
			chair = true
			drawer = true
			pillar_trim = true
			side_table = true

		[entries.wood_type.friendsandfoes]
			beehive = true

		[entries.wood_type.furnish]
			coffin = true
			cabinet = true
			wardrobe = true
			kitchen_cabinet = true
			stool = true
			bookshelf_chest = true
			log_bench = true
			shelf = true
			bench = true
			pedestal_table = true
			shutter = true
			ladder = true
			bedside_table = true
			square_table = true
			crate = true
			table = true
			chair = true

		[entries.wood_type.create]
			window_pane = true
			window = true

		[entries.wood_type.storagedrawers]
			half_drawers_1 = true
			half_drawers_4 = true
			half_drawers_2 = true
			trim = true
			full_drawers_2 = true
			full_drawers_4 = true
			full_drawers_1 = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

