
[Client]
	#Should coats, markings, speed, jump strength and health show up on certain O-Mount GUIs?
	"Mount GUI Extras" = true
	#Should Brand Tags render on animals that have been tagged?
	"Render Brand Tags" = true
	#Should Leg Bands render on Chickens that have been tagged?
	"Render Chicken Leg Bands" = true
	#Should Neck Tags render on Chickens that have been tagged? Might be good for those who have trouble seeing leg bands.
	"Render Chicken Neck Tags" = false
	#Should text that states the gender of an O-Mount render along with the colored dot?
	"Visual Accessibility Gender Text" = false
	#Should horse armor be 'lighter' visually? This doesn't change the protection the armor gives.
	"Minimal Horse Armor" = false
	#Should horse saddles include a breast collar & hip straps?
	"Horse Saddle Extras" = true
	#Should horse saddles take on the old, 'legacy' design? (Pre-2.1)
	"Legacy Horse Saddles" = false

