
["Button Settings"]
	#X position of the Passive Skill Tree button in the inventory screen
	#Range: > 0
	buttonX = 1000
	#Y position of the Passive Skill Tree button in the inventory screen
	#Range: > 0
	buttonY = 1000

