
["Skill Points"]
	#Range: 1 ~ 1000
	"Maximum skill points" = 150
	#Range: > 0
	"First skill point cost" = 15
	#Range: > 0
	"Last skill point cost" = 2000
	#You can set cost for each skill point instead
	"Use skill points costs array" = false
	#This list's size must be equal to maximum skill points.
	"Levelup costs" = [15, 19, 24, 30, 37, 45, 54, 64, 75, 87, 100, 114, 129, 145, 162, 180, 199, 219, 240, 262, 285, 309, 334, 360, 387, 415, 444, 474, 505, 537, 570, 604, 639, 675, 712, 750, 789, 829, 870, 912, 955, 999, 1044, 1090, 1137, 1185, 1234, 1284, 1335, 1387, 1440, 1494, 1549, 1605, 1662, 1720, 1779, 1839, 1900, 1962, 2025, 2089, 2154, 2220, 2287, 2355, 2424, 2494, 2565, 2637, 2710, 2784, 2859, 2935, 3012, 3090, 3169, 3249, 3330, 3412, 3495, 3579, 3664, 3750, 3837, 3925, 4014, 4104, 4195, 4287, 4380, 4474, 4569, 4665, 4762, 4860, 4959, 5059, 5160, 5262, 5365, 5469, 5574, 5680, 5787, 5895, 6004, 6114, 6225, 6337, 6450, 6564, 6679, 6795, 6912, 7030, 7149, 7269, 7390, 7512, 7635, 7759, 7884, 8010, 8137, 8265, 8394, 8524, 8655, 8787, 8920, 9054, 9189, 9325, 9462, 9600, 9739, 9879, 10020, 10162, 10305, 10449, 10594, 10740, 10887, 11035, 11184, 11334, 11485, 11637, 11790, 11944, 12099, 12255, 12412, 12570, 12729, 12889, 13050, 13212, 13375, 13539, 13704, 13870, 14037, 14205, 14374, 14544, 14715, 14887, 15060]
	#Disabling this will remove chat messages when you gain a skill point.
	"Show chat messages" = true
	#Warning: If you disable this make sure you make alternative way of getting skill points.
	"Enable exprerience exchange for skill points" = false

[Gems]
	#Range: 0.0 ~ 1.0
	"Base drop chance" = 0.0

[Equipment]
	#Range: 0 ~ 4
	"Default Helmets Sockets" = 1
	#Range: 0 ~ 4
	"Default Chestplates Sockets" = 1
	#Range: 0 ~ 4
	"Default Leggings Sockets" = 0
	#Range: 0 ~ 4
	"Default Boots Sockets" = 1
	#Range: 0 ~ 4
	"Default Weapons Sockets" = 1
	#Range: 0 ~ 4
	"Default Shields Sockets" = 1
	#Range: 0 ~ 4
	"Default Rings Sockets" = 1
	#Range: 0 ~ 4
	"Default Necklaces Sockets" = 1
	#You can remove sockets from items here
	#Example: Blacklisting specific items: ["minecraft:diamond_hoe", "minecraft:golden_hoe"]
	#Example: Blacklisting whole mod: ["<mod_id>:*"]
	#Example: Blacklisting all items: ["*:*"]
	"IDs of items that shouldn't have sockets" = []

#You can force items from other mods into equipmentType categories here
["Amnesia Scroll"]
	#How much levels (percentage) player lose using amnesia scroll
	#Range: 0.0 ~ 1.0
	"Amnesia scroll penalty" = 0.2
	"Drop amnesia scrolls from the Ender Dragon" = true

[Experience]
	#Range: 0.0 ~ 1.0
	"Grindstone experience multiplier" = 0.1

[Mixtures]
	#Range: 0.0 ~ 2.0
	"Effects duration multiplier" = 1.0
	#Range: 0.0 ~ 2.0
	"Effects strength multiplier" = 1.0

